SELECT * FROM CATEGORYS;
SELECT COUNT(*) FROM CATEGORYS;

SELECT * FROM CLIENT;
SELECT COUNT(*) FROM CLIENT;

SELECT * FROM ORDER_PRODUCT;
SELECT COUNT(*) FROM ORDER_PRODUCT;

SELECT * FROM ORDERS;
SELECT COUNT(*) FROM ORDERS;

SELECT * FROM ORDER_SUPPLIER;
SELECT COUNT(*) FROM ORDER_SUPPLIER;

SELECT * FROM ORDER_WORKER;
SELECT COUNT(*) FROM ORDER_WORKER;

SELECT * FROM PRODUCTS;
SELECT COUNT(*) FROM PRODUCTS;

SELECT * FROM PURCHASE;
SELECT COUNT(*) FROM PURCHASE;

SELECT * FROM PURCHASE_CLIENT;
SELECT COUNT(*) FROM PURCHASE_CLIENT;

SELECT * FROM PURCHASE_PRODUCT;
SELECT COUNT(*) FROM PURCHASE_PRODUCT;

SELECT * FROM PURCHASE_WORKER;
SELECT COUNT(*) FROM PURCHASE_WORKER;

SELECT * FROM SUPPLIER;
SELECT COUNT(*) FROM SUPPLIER;

SELECT * FROM WORKER;
SELECT COUNT(*) FROM WORKER;




